{{- if eq (include "xeronmx.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xeronmx.fullname" . }}
  labels:
    {{- include "xeronmx.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.cluster.secret }}
  XERONMX_CLUSTER_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.oidc.clientSecret }}
  XERONMX_OIDC_CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.metrics.token }}
  XERONMX_METRICS_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.alerts.email.password }}
  XERONMX_ALERTS_EMAIL_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.spam.password }}
  XERONMX_SPAM_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
